import { writeFileSync } from "fs";

/**
 * Generate TypeScript declaration file for sprite.svg
 */
function generateSpriteDeclaration() {
  const declarationContent = `/* tslint:disable */
/* eslint-disable */
/* This file is automatically generated and should not be edited. */

declare const spriteHref: string;
export default spriteHref;
`;

  writeFileSync("sprites.d.ts", declarationContent);
  console.log("Generated sprites.d.ts");
}

generateSpriteDeclaration();
