export const componentSections = [
  "Actions",
  "Forms & Inputs",
  "Images & Icons",
  "Layouts & Structure",
  "Lists & Tables",
  "Navigation",
  "Overlays",
  "Private",
  "Selections",
  "Status & Feedback",
  "Text & Typography",
  "Themes",
  "Utilities",
];
