export const componentList = [
  {
    title: "AnimatedPresence",
    to: "/components/AnimatedPresence",
    imageURL: "/Animation.png",
    additionalMatches: ["Motion", "Animation", "Reveal"],
    sections: [],
  },
  {
    title: "AnimatedSwitcher",
    to: "/components/AnimatedSwitcher",
    imageURL: "/Animation.png",
    additionalMatches: ["Motion", "Animation"],
    sections: [],
  },
  {
    title: "Autocomplete",
    to: "/components/Autocomplete",
    imageURL: "/Autocomplete.png",
    sections: ["Forms and Inputs"],
  },
  {
    title: "Avatar",
    to: "/components/Avatar",
    imageURL: "/Avatar.png",
    sections: ["Images and Icons"],
  },
  {
    title: "Banner",
    to: "/components/Banner",
    imageURL: "/Banner.png",
    sections: [],
  },
  {
    title: "Box",
    to: "/components/Box",
    imageURL: "/Box.png",
    sections: ["Layouts and Structure"],
  },
  {
    title: "Button",
    to: "/components/Button",
    imageURL: "/Button.png",
    sections: ["Actions"],
  },
  {
    title: "ButtonDismiss",
    to: "/components/ButtonDismiss",
    imageURL: "/ButtonDismiss.png",
    additionalMatches: ["Close", "Dismiss", "Remove"],
    sections: [],
  },
  {
    title: "Card",
    to: "/components/Card",
    imageURL: "/Card.png",
    sections: ["Layouts and Structure"],
  },
  {
    title: "Checkbox",
    to: "/components/Checkbox",
    imageURL: "/Checkbox.png",
    sections: [],
  },
  {
    title: "Chip",
    to: "/components/Chip",
    imageURL: "/Chip.png",
    additionalMatches: ["Pill", "Badge", "Tag"],
    sections: [],
  },
  {
    title: "Chips",
    to: "/components/Chips",
    imageURL: "/Chips.png",
    additionalMatches: ["Pill", "Badge", "Tag"],
    sections: [],
  },
  {
    title: "Combobox",
    to: "/components/Combobox",
    imageURL: "/Combobox.png",
    sections: [],
  },
  {
    title: "ConfirmationModal",
    to: "/components/ConfirmationModal",
    imageURL: "/ConfirmationModal.png",
    additionalMatches: ["Confirm", "Prompt", "Modal"],
    sections: [],
  },
  {
    title: "Countdown",
    to: "/components/Countdown",
    imageURL: "/Countdown.png",
    sections: [],
  },
  {
    title: "DataDump",
    to: "/components/DataDump",
    imageURL: "/DataDump.png",
    sections: [],
  },
  {
    title: "DataList",
    to: "/components/DataList",
    imageURL: "/DataList.png",
    sections: [],
  },
  {
    title: "DataTable",
    to: "/components/DataTable",
    imageURL: "/DataTable.png",
    sections: [],
  },
  {
    title: "DatePicker",
    to: "/components/DatePicker",
    imageURL: "/DatePicker.png",
    sections: [],
  },
  {
    title: "DescriptionList",
    to: "/components/DescriptionList",
    imageURL: "/DescriptionList.png",
    sections: [],
  },
  {
    title: "Disclosure",
    to: "/components/Disclosure",
    imageURL: "/Disclosure.png",
    additionalMatches: [
      "Accordion",
      "Collapsable",
      "Expandable",
      "Toggle",
      "Reveal",
    ],
    sections: [],
  },
  {
    title: "Divider",
    to: "/components/Divider",
    imageURL: "/Divider.png",
    sections: [],
  },
  {
    title: "Drawer",
    to: "/components/Drawer",
    imageURL: "/Drawer.png",
    sections: [],
  },
  {
    title: "Emphasis",
    to: "/components/Emphasis",
    imageURL: "/Emphasis.png",
    additionalMatches: ["Highlight", "Strong", "Bold", "Italic"],
    sections: [],
  },
  {
    title: "FeatureSwitch",
    to: "/components/FeatureSwitch",
    imageURL: "/FeatureSwitch.png",
    sections: [],
  },
  {
    title: "Flex",
    to: "/components/Flex",
    imageURL: "/Flex.png",
    sections: [],
  },
  {
    title: "Form",
    to: "/components/Form",
    imageURL: "/Form.png",
    sections: ["Forms and Inputs"],
  },
  {
    title: "FormatDate",
    to: "/components/FormatDate",
    imageURL: "/FormatDate.png",
    sections: [],
  },
  {
    title: "FormatEmail",
    to: "/components/FormatEmail",
    imageURL: "/FormatEmail.png",
    sections: [],
  },
  {
    title: "FormatFile",
    to: "/components/FormatFile",
    imageURL: "/FormatFile.png",
    sections: ["Images and Icons"],
  },
  {
    title: "FormatRelativeDateTime",
    to: "/components/FormatRelativeDateTime",
    imageURL: "/FormatRelativeDateTime.png",
    sections: [],
  },
  {
    title: "FormatTime",
    to: "/components/FormatTime",
    imageURL: "/FormatTime.png",
    sections: [],
  },
  {
    title: "FormField",
    to: "/components/FormField",
    imageURL: "/FormField.png",
    sections: [],
  },
  {
    title: "Gallery",
    to: "/components/Gallery",
    imageURL: "/Gallery.png",
    sections: ["Images and Icons"],
  },
  {
    title: "Glimmer",
    to: "/components/Glimmer",
    imageURL: "/Glimmer.png",
    additionalMatches: ["Skeleton", "Shimmer"],
    sections: [],
  },
  {
    title: "Grid",
    to: "/components/Grid",
    imageURL: "/Grid.png",
    sections: [],
  },
  {
    title: "Heading",
    to: "/components/Heading",
    imageURL: "/Heading.png",
    additionalMatches: ["Title", "Subtitle", "Header"],
    sections: [],
  },
  {
    title: "Icon",
    to: "/components/Icon",
    imageURL: "/Icon.png",
    sections: ["Images and Icons"],
  },
  {
    title: "InlineLabel",
    to: "/components/InlineLabel",
    imageURL: "/InlineLabel.png",
    additionalMatches: [
      "Tag",
      "Label",
      "Chip",
      "Badge",
      "Pill",
      "Status Label",
      "Status",
    ],
    sections: [],
  },
  {
    title: "InputAvatar",
    to: "/components/InputAvatar",
    imageURL: "/InputAvatar.png",
    sections: ["Forms and Inputs"],
  },
  {
    title: "InputDate",
    to: "/components/InputDate",
    imageURL: "/InputDate.png",
    additionalMatches: ["Datepicker", "Datetime Picker", "Calendar"],
    sections: ["Forms and Inputs"],
  },
  {
    title: "InputEmail",
    to: "/components/InputEmail",
    imageURL: "/InputEmail.png",
    sections: ["Forms and Inputs"],
  },
  {
    title: "InputFile",
    to: "/components/InputFile",
    imageURL: "/InputFile.png",
    sections: ["Forms and Inputs"],
  },
  {
    title: "InputGroup",
    to: "/components/InputGroup",
    imageURL: "/InputGroup.png",
    sections: ["Forms and Inputs"],
  },
  {
    title: "InputNumber",
    to: "/components/InputNumber",
    imageURL: "/InputNumber.png",
    sections: ["Forms and Inputs"],
  },
  {
    title: "InputPassword",
    to: "/components/InputPassword",
    imageURL: "/InputPassword.png",
    sections: ["Forms and Inputs"],
  },
  {
    title: "InputPhoneNumber",
    to: "/components/InputPhoneNumber",
    imageURL: "/InputPhoneNumber.png",
    sections: ["Forms and Inputs"],
  },
  {
    title: "InputText",
    to: "/components/InputText",
    imageURL: "/InputText.png",
    sections: ["Forms and Inputs"],
  },
  {
    title: "InputTime",
    to: "/components/InputTime",
    imageURL: "/InputTime.png",
    sections: ["Forms and Inputs"],
  },
  {
    title: "InputValidation",
    to: "/components/InputValidation",
    imageURL: "/InputValidation.png",
    sections: ["Forms and Inputs"],
  },
  {
    title: "LightBox",
    to: "/components/LightBox",
    imageURL: "/LightBox.png",
    sections: ["Images and Icons"],
  },
  {
    title: "Link",
    to: "/components/Link",
    imageURL: "/Link.png",
    additionalMatches: ["Anchor", "URL"],
    sections: [],
  },
  {
    title: "List",
    to: "/components/List",
    imageURL: "/List.png",
    sections: [],
  },
  {
    title: "Markdown",
    to: "/components/Markdown",
    imageURL: "/Markdown.png",
    sections: [],
  },
  {
    title: "Menu",
    to: "/components/Menu",
    imageURL: "/Menu.png",
    sections: [],
  },
  {
    title: "Modal",
    to: "/components/Modal",
    imageURL: "/Modal.png",
    sections: [],
  },
  {
    title: "MultiSelect",
    to: "/components/MultiSelect",
    imageURL: "/MultiSelect.png",
    sections: [],
  },
  {
    title: "Popover",
    to: "/components/Popover",
    imageURL: "/Popover.png",
    sections: [],
  },
  {
    title: "ProgressBar",
    to: "/components/ProgressBar",
    imageURL: "/ProgressBar.png",
    additionalMatches: ["Progress", "Loader"],
    sections: [],
  },
  {
    title: "RadioGroup",
    to: "/components/RadioGroup",
    imageURL: "/RadioGroup.png",
    sections: ["Forms and Inputs"],
  },
  {
    title: "RecurringSelect",
    to: "/components/RecurringSelect",
    imageURL: "/RecurringSelect.png",
    sections: [],
  },
  {
    title: "SegmentedControl",
    to: "/components/SegmentedControl",
    imageURL: "/SegmentedControl.png",
    sections: [],
  },
  {
    title: "Select",
    to: "/components/Select",
    imageURL: "/Select.png",
    sections: [],
  },
  {
    title: "Spinner",
    to: "/components/Spinner",
    imageURL: "/Spinner.png",
    additionalMatches: ["Loader", "Loading", "Twirly", "Wait", "Busy"],
    sections: [],
  },
  {
    title: "StatusIndicator",
    to: "/components/StatusIndicator",
    imageURL: "/StatusIndicator.png",
    sections: [],
  },
  {
    title: "StatusLabel",
    to: "/components/StatusLabel",
    imageURL: "/StatusLabel.png",
    additionalMatches: ["Badge", "Pill", "Tag", "InlineLabel", "Inline Label"],
    sections: [],
  },
  {
    title: "Switch",
    to: "/components/Switch",
    imageURL: "/Switch.png",
    additionalMatches: ["Toggle"],
    sections: [],
  },
  {
    title: "Table",
    to: "/components/Table",
    imageURL: "/Table.png",
    sections: [],
  },
  {
    title: "Tabs",
    to: "/components/Tabs",
    imageURL: "/Tabs.png",
    sections: [],
  },
  {
    title: "Text",
    to: "/components/Text",
    imageURL: "/Text.png",
    sections: [],
  },
  {
    title: "Toast",
    to: "/components/Toast",
    imageURL: "/Toast.png",
    sections: [],
  },
  {
    title: "Tooltip",
    to: "/components/Tooltip",
    imageURL: "/Tooltip.png",
    sections: [],
  },
  {
    title: "Typography",
    to: "/components/Typography",
    imageURL: "/Typography.png",
    sections: [],
  },
];
