export const componentList = [
  {
    title: "ActionItem",
    to: "/components/ActionItem",
    imageURL: "/ActionItem.png",
    sections: ["Layouts & Structure"],
  },
  {
    title: "ActionItemGroup",
    to: "/components/ActionItemGroup",
    imageURL: "/ActionItemGroup.png",
    sections: ["Layouts & Structure"],
  },
  {
    title: "ActionLabel",
    to: "/components/ActionLabel",
    imageURL: "/ActionLabel.png",
    sections: ["Actions"],
    additionalMatches: ["Button"],
  },
  {
    title: "ActivityIndicator",
    to: "/components/ActivityIndicator",
    imageURL: "/ActivityIndicator.png",
    sections: ["Status & Feedback"],
    additionalMatches: ["Loader", "Loading", "Busy", "Spinner"],
  },
  {
    title: "AnimatedPresence",
    to: "/components/AnimatedPresence",
    imageURL: "/Animation.png",
    additionalMatches: ["Motion", "Animation", "Reveal"],
    sections: ["Utilities"],
  },
  {
    title: "AnimatedSwitcher",
    to: "/components/AnimatedSwitcher",
    imageURL: "/Animation.png",
    additionalMatches: ["Motion", "Animation"],
    sections: ["Utilities"],
  },
  {
    title: "AtlantisThemeContext",
    to: "/components/AtlantisThemeContext",
    imageURL: "/AtlantisThemeContext.png",
    additionalMatches: ["Theme", "Dark Mode", "Light Mode"],
    sections: ["Themes"],
  },
  {
    title: "Autocomplete",
    to: "/components/Autocomplete",
    imageURL: "/Autocomplete.png",
    sections: ["Forms & Inputs"],
    additionalMatches: ["Search", "Typeahead", "Suggest"],
  },
  {
    title: "AutoLink",
    to: "/components/AutoLink",
    imageURL: "/AutoLink.png",
    sections: ["Text & Typography"],
    additionalMatches: ["Link", "URL", "Text", "Phone", "Email"],
  },
  {
    title: "Avatar",
    to: "/components/Avatar",
    imageURL: "/Avatar.png",
    sections: ["Images & Icons"],
    additionalMatches: ["User", "Facepile", "Profile"],
  },
  {
    title: "Banner",
    to: "/components/Banner",
    imageURL: "/Banner.png",
    sections: ["Status & Feedback"],
    additionalMatches: ["Flash", "Alert", "Notification", "Hero"],
  },
  {
    title: "Box",
    to: "/components/Box",
    imageURL: "/Box.png",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Layout", "Container", "Stack", "Wrapper"],
  },
  {
    title: "BottomSheet",
    to: "/components/BottomSheet",
    imageURL: "/BottomSheet.png",
    sections: ["Selections"],
    additionalMatches: ["Drawer", "Panel", "Overlay", "Modal"],
  },
  {
    title: "Button",
    to: "/components/Button",
    imageURL: "/Button.png",
    sections: ["Actions"],
    additionalMatches: ["Action"],
  },
  {
    title: "ButtonDismiss",
    to: "/components/ButtonDismiss",
    imageURL: "/ButtonDismiss.png",
    additionalMatches: ["Close", "Dismiss", "Remove"],
    sections: ["Private"],
  },
  {
    title: "ButtonGroup",
    to: "/components/ButtonGroup",
    imageURL: "/ButtonGroup.png",
    sections: ["Actions"],
    additionalMatches: ["Action", "Layout", "Wrapper"],
  },
  {
    title: "Card",
    to: "/components/Card",
    imageURL: "/Card.png",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Tile"],
  },
  {
    title: "ContentBlock",
    to: "/components/ContentBlock",
    imageURL: "/Placeholder.png",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Layout", "Container", "Stack", "Wrapper"],
  },
  {
    title: "Checkbox",
    to: "/components/Checkbox",
    imageURL: "/Checkbox.png",
    sections: ["Selections"],
    additionalMatches: ["Select"],
  },
  {
    title: "Chip",
    to: "/components/Chip",
    imageURL: "/Chip.png",
    sections: ["Selections"],
    additionalMatches: ["Pill", "Badge", "Tag", "Select"],
  },
  {
    title: "Chips",
    to: "/components/Chips",
    imageURL: "/Chips.png",
    additionalMatches: ["Pill", "Badge", "Tag"],
    sections: ["Selections"],
  },
  {
    title: "Cluster",
    to: "/components/Cluster",
    imageURL: "/Placeholder.png",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Grid", "Columns", "Rows"],
  },
  {
    title: "Combobox",
    to: "/components/Combobox",
    imageURL: "/Combobox.png",
    sections: ["Selections"],
    additionalMatches: ["Dropdown", "Picker", "Select"],
  },
  {
    title: "ConfirmationModal",
    to: "/components/ConfirmationModal",
    imageURL: "/ConfirmationModal.png",
    additionalMatches: ["Confirm", "Prompt", "Modal"],
    sections: ["Overlays"],
  },
  {
    title: "Container",
    to: "/components/Container",
    imageURL: "/Placeholder.png",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Layout", "Container", "Stack", "Query"],
  },
  {
    title: "Content",
    to: "/components/Content",
    imageURL: "/Content.png",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Stack", "Layout", "Container", "Wrapper", "Spacing"],
  },
  {
    title: "ContentOverlay",
    to: "/components/ContentOverlay",
    imageURL: "/ContentOverlay.png",
    sections: ["Overlays"],
  },
  {
    title: "Countdown",
    to: "/components/Countdown",
    imageURL: "/Countdown.png",
    sections: ["Utilities"],
    additionalMatches: ["Timer", "Time", "Clock"],
  },
  {
    title: "Cover",
    to: "/components/Cover",
    imageURL: "/Placeholder.png",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Layout", "Container", "Stack", "Wrapper"],
  },
  {
    title: "DataDump",
    to: "/components/DataDump",
    imageURL: "/DataDump.png",
    sections: ["Utilities"],
  },
  {
    title: "DataList",
    to: "/components/DataList",
    imageURL: "/DataList.png",
    sections: ["Lists & Tables"],
    additionalMatches: ["Thicklist", "Table"],
  },
  {
    title: "DataTable",
    to: "/components/DataTable",
    imageURL: "/DataTable.png",
    sections: ["Lists & Tables"],
    additionalMatches: ["Thicklist", "Table"],
  },
  {
    title: "DatePicker",
    to: "/components/DatePicker",
    imageURL: "/DatePicker.png",
    sections: ["Selections"],
    additionalMatches: ["Calendar", "Date Picker", "Date Input"],
  },
  {
    title: "DescriptionList",
    to: "/components/DescriptionList",
    imageURL: "/DescriptionList.png",
    sections: ["Lists & Tables"],
    additionalMatches: ["Simple List", "Key Value Pair", "Definition List"],
  },
  {
    title: "Disclosure",
    to: "/components/Disclosure",
    imageURL: "/Disclosure.png",
    additionalMatches: [
      "Accordion",
      "Collapsable",
      "Expandable",
      "Toggle",
      "Reveal",
    ],
    sections: ["Layouts & Structure"],
  },
  {
    title: "Divider",
    to: "/components/Divider",
    imageURL: "/Divider.png",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Separator", "Line", "Rule", "Border", "HR"],
  },
  {
    title: "Drawer",
    to: "/components/Drawer",
    imageURL: "/Drawer.png",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Aside", "Panel", "Flyout"],
  },
  {
    title: "Emphasis",
    to: "/components/Emphasis",
    imageURL: "/Emphasis.png",
    additionalMatches: ["Highlight", "Strong", "Bold", "Italic"],
    sections: ["Text & Typography"],
  },
  {
    title: "EmptyState",
    to: "/components/EmptyState",
    imageURL: "/EmptyState.png",
    additionalMatches: ["No", "None", "Nada", "Nothing"],
    sections: ["Status & Feedback"],
  },
  {
    title: "FeatureSwitch",
    to: "/components/FeatureSwitch",
    imageURL: "/FeatureSwitch.png",
    sections: ["Selections"],
  },
  {
    title: "Flex",
    to: "/components/Flex",
    imageURL: "/Flex.png",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Layout", "Stack", "Container"],
  },
  {
    title: "Frame",
    to: "/components/Frame",
    imageURL: "/Placeholder.png",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Layout", "Stack", "Container"],
  },
  {
    title: "Form",
    to: "/components/Form",
    imageURL: "/Form.png",
    sections: ["Forms & Inputs"],
  },
  {
    title: "FormatDate",
    to: "/components/FormatDate",
    imageURL: "/FormatDate.png",
    sections: ["Utilities"],
  },
  {
    title: "FormatEmail",
    to: "/components/FormatEmail",
    imageURL: "/FormatEmail.png",
    sections: ["Utilities"],
  },
  {
    title: "FormatFile",
    to: "/components/FormatFile",
    imageURL: "/FormatFile.png",
    sections: ["Images & Icons"],
    additionalMatches: ["Display", "Upload", "Thumbnail", "Image"],
  },
  {
    title: "FormatRelativeDateTime",
    to: "/components/FormatRelativeDateTime",
    imageURL: "/FormatRelativeDateTime.png",
    sections: ["Utilities"],
  },
  {
    title: "FormatTime",
    to: "/components/FormatTime",
    imageURL: "/FormatTime.png",
    sections: ["Utilities"],
  },
  {
    title: "FormField",
    to: "/components/FormField",
    imageURL: "/FormField.png",
    sections: ["Private"],
  },
  {
    title: "Gallery",
    to: "/components/Gallery",
    imageURL: "/Gallery.png",
    sections: ["Images & Icons"],
    additionalMatches: [
      "ThumbnailList",
      "ImageList",
      "Carousel",
      "Image",
      "Thumbnail",
      "Photo",
    ],
  },
  {
    title: "Glimmer",
    to: "/components/Glimmer",
    imageURL: "/Glimmer.png",
    additionalMatches: ["Skeleton", "Shimmer"],
    sections: ["Status & Feedback"],
  },
  {
    title: "Grid",
    to: "/components/Grid",
    imageURL: "/Grid.png",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Layout", "Columns"],
  },
  {
    title: "Heading",
    to: "/components/Heading",
    imageURL: "/Heading.png",
    sections: ["Text & Typography"],
    additionalMatches: [
      "Title",
      "Subtitle",
      "Header",
      "H1",
      "H2",
      "H3",
      "H4",
      "H5",
      "H6",
    ],
  },
  {
    title: "Icon",
    to: "/components/Icon",
    imageURL: "/Icon.png",
    sections: ["Images & Icons"],
    additionalMatches: ["Symbol"],
  },
  {
    title: "IconButton",
    to: "/components/IconButton",
    imageURL: "/IconButton.png",
    sections: ["Actions"],
  },
  {
    title: "InlineLabel",
    to: "/components/InlineLabel",
    imageURL: "/InlineLabel.png",
    additionalMatches: [
      "Tag",
      "Label",
      "Chip",
      "Badge",
      "Pill",
      "Status Label",
      "Status",
    ],
    sections: ["Status & Feedback"],
  },
  {
    title: "InputAvatar",
    to: "/components/InputAvatar",
    imageURL: "/InputAvatar.png",
    sections: ["Forms & Inputs"],
  },
  {
    title: "InputCurrency",
    to: "/components/InputCurrency",
    imageURL: "/InputCurrency.png",
    sections: ["Forms & Inputs"],
    additionalMatches: ["Money", "Dollar", "Currency"],
  },
  {
    title: "InputDate",
    to: "/components/InputDate",
    imageURL: "/InputDate.png",
    additionalMatches: ["Datepicker", "Datetime Picker", "Calendar"],
    sections: ["Forms & Inputs"],
  },
  {
    title: "InputEmail",
    to: "/components/InputEmail",
    imageURL: "/InputEmail.png",
    sections: ["Forms & Inputs"],
    additionalMatches: ["Email Input"],
  },
  {
    title: "InputFieldWrapper",
    to: "/components/InputFieldWrapper",
    imageURL: "/InputFieldWrapper.png",
    sections: ["Private"],
  },
  {
    title: "InputFile",
    to: "/components/InputFile",
    imageURL: "/InputFile.png",
    sections: ["Forms & Inputs"],
    additionalMatches: [
      "Uploader",
      "File Input",
      "File Uploader",
      "Upload",
      "Dropzone",
      "Image",
    ],
  },
  {
    title: "InputGroup",
    to: "/components/InputGroup",
    imageURL: "/InputGroup.png",
    sections: ["Forms & Inputs"],
    additionalMatches: ["Fieldset"],
  },
  {
    title: "InputNumber",
    to: "/components/InputNumber",
    imageURL: "/InputNumber.png",
    sections: ["Forms & Inputs"],
    additionalMatches: ["Number Input", "Numeric Input"],
  },
  {
    title: "InputNumber2",
    to: "/components/InputNumber2",
    imageURL: "/InputNumber.png",
    sections: ["Forms & Inputs"],
    additionalMatches: ["Number Input", "Numeric Input"],
  },
  {
    title: "InputPassword",
    to: "/components/InputPassword",
    imageURL: "/InputPassword.png",
    sections: ["Forms & Inputs"],
    additionalMatches: ["Password Input"],
  },
  {
    title: "InputPhoneNumber",
    to: "/components/InputPhoneNumber",
    imageURL: "/InputPhoneNumber.png",
    sections: ["Forms & Inputs"],
    additionalMatches: ["Phone Number Input"],
  },
  {
    title: "InputPressable",
    to: "/components/InputPressable",
    imageURL: "/InputPressable.png",
    sections: ["Forms & Inputs"],
  },
  {
    title: "InputSearch",
    to: "/components/InputSearch",
    imageURL: "/InputSearch.png",
    sections: ["Forms & Inputs"],
  },
  {
    title: "InputText",
    to: "/components/InputText",
    imageURL: "/InputText.png",
    sections: ["Forms & Inputs"],
    additionalMatches: [
      "Textfield",
      "Text Input",
      "Input",
      "Textbox",
      "Textarea",
      "Field",
    ],
  },
  {
    title: "InputTime",
    to: "/components/InputTime",
    imageURL: "/InputTime.png",
    sections: ["Forms & Inputs"],
    additionalMatches: ["Time Input", "Time Picker"],
  },
  {
    title: "InputValidation",
    to: "/components/InputValidation",
    imageURL: "/InputValidation.png",
    sections: ["Forms & Inputs"],
    additionalMatches: ["Field Error", "Error Message"],
  },
  {
    title: "LightBox",
    to: "/components/LightBox",
    imageURL: "/LightBox.png",
    sections: ["Images & Icons"],
    additionalMatches: [
      "Gallery",
      "Carousel",
      "Display",
      "Image",
      "Box Sizing",
      "Border Box",
    ],
  },
  {
    title: "Link",
    to: "/components/Link",
    imageURL: "/Link.png",
    additionalMatches: ["Anchor", "URL"],
    sections: ["Text & Typography"],
  },
  {
    title: "List",
    to: "/components/List",
    imageURL: "/List.png",
    sections: ["Lists & Tables"],
  },
  {
    title: "Markdown",
    to: "/components/Markdown",
    imageURL: "/Markdown.png",
    sections: ["Text & Typography"],
    additionalMatches: ["Text"],
  },
  {
    title: "Menu",
    to: "/components/Menu",
    imageURL: "/Menu.png",
    sections: ["Navigation"],
    additionalMatches: ["Dropdown"],
  },
  {
    title: "Modal",
    to: "/components/Modal",
    imageURL: "/Modal.png",
    sections: ["Overlays"],
    additionalMatches: ["Dialog", "Popup", "Overlay", "Confirm", "Alert"],
  },
  {
    title: "MultiSelect",
    to: "/components/MultiSelect",
    imageURL: "/MultiSelect.png",
    sections: ["Selections"],
    additionalMatches: ["Dropdown", "Menu"],
  },
  {
    title: "Page",
    to: "/components/Page",
    imageURL: "/Page.png",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Layout", "Container"],
  },
  {
    title: "Popover",
    to: "/components/Popover",
    imageURL: "/Popover.png",
    sections: ["Overlays"],
    additionalMatches: [
      "Dropdown",
      "Popup",
      "Tooltip",
      "Float",
      "Dialog",
      "Info",
    ],
  },
  {
    title: "ProgressBar",
    to: "/components/ProgressBar",
    imageURL: "/ProgressBar.png",
    sections: ["Status & Feedback"],
    additionalMatches: ["Progress", "Loader", "Stepper"],
  },
  {
    title: "RadioGroup",
    to: "/components/RadioGroup",
    imageURL: "/RadioGroup.png",
    sections: ["Forms & Inputs"],
    additionalMatches: ["Radio Button", "Select"],
  },
  {
    title: "RecurringSelect",
    to: "/components/RecurringSelect",
    imageURL: "/RecurringSelect.png",
    sections: ["Selections"],
    additionalMatches: ["Calendar", "Date Picker", "Schedule"],
  },
  {
    title: "ResponsiveSwitcher",
    to: "/components/ResponsiveSwitcher",
    imageURL: "/Placeholder.png",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Layout", "Container", "Stack", "Wrapper"],
  },
  {
    title: "SegmentedControl",
    to: "/components/SegmentedControl",
    imageURL: "/SegmentedControl.png",
    sections: ["Selections"],
    additionalMatches: ["Toggle", "Switch", "ViewControl", "TabControl", "Tab"],
  },
  {
    title: "Select",
    to: "/components/Select",
    imageURL: "/Select.png",
    sections: ["Selections"],
    additionalMatches: ["Dropdown", "Picker", "Menu"],
  },
  {
    title: "SideDrawer",
    to: "/components/SideDrawer",
    imageURL: "/SideDrawer.png",
    sections: ["Overlays"],
    additionalMatches: ["Drawer", "Panel", "Sidebar", "Flyout"],
  },
  {
    title: "SideKick",
    to: "/components/SideKick",
    imageURL: "/Placeholder.png",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Layout", "Container", "Stack", "Wrapper"],
  },
  {
    title: "Spinner",
    to: "/components/Spinner",
    imageURL: "/Spinner.png",
    sections: ["Status & Feedback"],
    additionalMatches: [
      "Loader",
      "Loading",
      "Twirly",
      "Wait",
      "Busy",
      "ActivityIndicator",
    ],
  },
  {
    title: "Stack",
    to: "/components/Stack",
    imageURL: "/Placeholder.png",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Layout", "Container", "Stack", "Wrapper"],
  },
  {
    title: "StatusIndicator",
    to: "/components/StatusIndicator",
    imageURL: "/StatusIndicator.png",
    sections: ["Status & Feedback"],
    additionalMatches: ["Badge", "Tag"],
  },
  {
    title: "StatusLabel",
    to: "/components/StatusLabel",
    imageURL: "/StatusLabel.png",
    additionalMatches: ["Badge", "Pill", "Tag", "InlineLabel", "Inline Label"],
    sections: ["Status & Feedback"],
  },
  {
    title: "Switch",
    to: "/components/Switch",
    imageURL: "/Switch.png",
    additionalMatches: ["Toggle"],
    sections: ["Selections"],
  },
  {
    title: "Table",
    to: "/components/Table",
    imageURL: "/Table.png",
    sections: ["Lists & Tables"],
  },
  {
    title: "Tabs",
    to: "/components/Tabs",
    imageURL: "/Tabs.png",
    sections: ["Navigation"],
    additionalMatches: ["Segmented Control"],
  },
  {
    title: "Text",
    to: "/components/Text",
    imageURL: "/Text.png",
    sections: ["Text & Typography"],
    additionalMatches: ["Paragraph", "Body Copy", "Typography"],
  },
  {
    title: "TextList",
    to: "/components/TextList",
    imageURL: "/TextList.png",
    sections: ["Lists & Tables"],
    additionalMatches: ["Bullet", "Unordered", "Ordered"],
  },
  {
    title: "ThumbnailList",
    to: "/components/ThumbnailList",
    imageURL: "/ThumbnailList.png",
    sections: ["Images & Icons"],
    additionalMatches: ["Gallery", "Image", "Photo"],
  },
  {
    title: "Tiles",
    to: "/components/Tiles",
    imageURL: "/Placeholder.png",
    sections: ["Layouts & Structure"],
    additionalMatches: ["Layout", "Container", "Stack", "Wrapper"],
  },
  {
    title: "Toast",
    to: "/components/Toast",
    imageURL: "/Toast.png",
    sections: ["Status & Feedback"],
    additionalMatches: [
      "Alert",
      "Notification",
      "Flash",
      "Snackbar",
      "Message",
    ],
  },
  {
    title: "Tooltip",
    to: "/components/Tooltip",
    imageURL: "/Tooltip.png",
    sections: ["Overlays"],
    additionalMatches: ["Popup", "Hover", "Popover", "Info"],
  },
  {
    title: "Typography",
    to: "/components/Typography",
    imageURL: "/Typography.png",
    sections: ["Text & Typography"],
  },
];
