export const componentGroupings = {
  Layout: ["Box", "Grid", "Stack", "Flex", "GridItem", "StackItem", "FlexItem"],
  Navigation: [
    "Breadcrumb",
    "Link",
    "Menu",
    "MenuItem",
    "MenuList",
    "MenuButton",
    "MenuDivider",
    "MenuGroup",
  ],
  "Data Display": [
    "Badge",
    "Avatar",
    "Chip",
    "Tag",
    "Card",
    "Table",
    "Header",
    "Row",
    "Cell",
    "Body",
    "Footer",
    "CellNumeric",
    "CellCurrency",
  ],
  Feedback: [
    "Banner",
    "Toast",
    "Modal",
    "Dialog",
    "Tooltip",
    "Popover",
    "Drawer",
  ],
  Form: [
    "Input",
    "Textarea",
    "Select",
    "Checkbox",
    "Radio",
    "Switch",
    "Autocomplete",
    "Button",
    "ButtonDismiss",
  ],
  Typography: [
    "Text",
    "Heading",
    "Paragraph",
    "Link",
    "Label",
    "Caption",
    "Status",
  ],
  Motion: ["AnimatedPresence", "AnimatedSwitcher", "Motion", "Reveal"],
};
