/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeGuideRouteImport } from './routes/welcome-guide'
import { Route as ComponentNotFoundRouteImport } from './routes/component-not-found'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisualTestsIndexRouteImport } from './routes/visual-tests/index'
import { Route as PatternsIndexRouteImport } from './routes/patterns/index'
import { Route as PackagesIndexRouteImport } from './routes/packages/index'
import { Route as HooksIndexRouteImport } from './routes/hooks/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as DesignIndexRouteImport } from './routes/design/index'
import { Route as ContentIndexRouteImport } from './routes/content/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as ChangelogIndexRouteImport } from './routes/changelog/index'
import { Route as VisualTestsPathRouteImport } from './routes/visual-tests/$path'
import { Route as PatternsNameRouteImport } from './routes/patterns/$name'
import { Route as PackagesNameRouteImport } from './routes/packages/$name'
import { Route as HooksNameRouteImport } from './routes/hooks/$name'
import { Route as GuidesNameRouteImport } from './routes/guides/$name'
import { Route as DesignNameRouteImport } from './routes/design/$name'
import { Route as ContentNameRouteImport } from './routes/content/$name'
import { Route as ComponentsNameRouteImport } from './routes/components/$name'
import { Route as ChangelogNameRouteImport } from './routes/changelog/$name'
import { Route as ComponentsNameTabRouteImport } from './routes/components/$name/$tab'

const WelcomeGuideRoute = WelcomeGuideRouteImport.update({
  id: '/welcome-guide',
  path: '/welcome-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentNotFoundRoute = ComponentNotFoundRouteImport.update({
  id: '/component-not-found',
  path: '/component-not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualTestsIndexRoute = VisualTestsIndexRouteImport.update({
  id: '/visual-tests/',
  path: '/visual-tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsIndexRoute = PatternsIndexRouteImport.update({
  id: '/patterns/',
  path: '/patterns/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIndexRoute = PackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksIndexRoute = HooksIndexRouteImport.update({
  id: '/hooks/',
  path: '/hooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIndexRoute = DesignIndexRouteImport.update({
  id: '/design/',
  path: '/design/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentIndexRoute = ContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualTestsPathRoute = VisualTestsPathRouteImport.update({
  id: '/visual-tests/$path',
  path: '/visual-tests/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsNameRoute = PatternsNameRouteImport.update({
  id: '/patterns/$name',
  path: '/patterns/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesNameRoute = PackagesNameRouteImport.update({
  id: '/packages/$name',
  path: '/packages/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksNameRoute = HooksNameRouteImport.update({
  id: '/hooks/$name',
  path: '/hooks/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesNameRoute = GuidesNameRouteImport.update({
  id: '/guides/$name',
  path: '/guides/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignNameRoute = DesignNameRouteImport.update({
  id: '/design/$name',
  path: '/design/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentNameRoute = ContentNameRouteImport.update({
  id: '/content/$name',
  path: '/content/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsNameRoute = ComponentsNameRouteImport.update({
  id: '/components/$name',
  path: '/components/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogNameRoute = ChangelogNameRouteImport.update({
  id: '/changelog/$name',
  path: '/changelog/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsNameTabRoute = ComponentsNameTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => ComponentsNameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/component-not-found': typeof ComponentNotFoundRoute
  '/welcome-guide': typeof WelcomeGuideRoute
  '/changelog/$name': typeof ChangelogNameRoute
  '/components/$name': typeof ComponentsNameRouteWithChildren
  '/content/$name': typeof ContentNameRoute
  '/design/$name': typeof DesignNameRoute
  '/guides/$name': typeof GuidesNameRoute
  '/hooks/$name': typeof HooksNameRoute
  '/packages/$name': typeof PackagesNameRoute
  '/patterns/$name': typeof PatternsNameRoute
  '/visual-tests/$path': typeof VisualTestsPathRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/content/': typeof ContentIndexRoute
  '/design/': typeof DesignIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/hooks/': typeof HooksIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/patterns/': typeof PatternsIndexRoute
  '/visual-tests/': typeof VisualTestsIndexRoute
  '/components/$name/$tab': typeof ComponentsNameTabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/component-not-found': typeof ComponentNotFoundRoute
  '/welcome-guide': typeof WelcomeGuideRoute
  '/changelog/$name': typeof ChangelogNameRoute
  '/components/$name': typeof ComponentsNameRouteWithChildren
  '/content/$name': typeof ContentNameRoute
  '/design/$name': typeof DesignNameRoute
  '/guides/$name': typeof GuidesNameRoute
  '/hooks/$name': typeof HooksNameRoute
  '/packages/$name': typeof PackagesNameRoute
  '/patterns/$name': typeof PatternsNameRoute
  '/visual-tests/$path': typeof VisualTestsPathRoute
  '/changelog': typeof ChangelogIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/content': typeof ContentIndexRoute
  '/design': typeof DesignIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/hooks': typeof HooksIndexRoute
  '/packages': typeof PackagesIndexRoute
  '/patterns': typeof PatternsIndexRoute
  '/visual-tests': typeof VisualTestsIndexRoute
  '/components/$name/$tab': typeof ComponentsNameTabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/component-not-found': typeof ComponentNotFoundRoute
  '/welcome-guide': typeof WelcomeGuideRoute
  '/changelog/$name': typeof ChangelogNameRoute
  '/components/$name': typeof ComponentsNameRouteWithChildren
  '/content/$name': typeof ContentNameRoute
  '/design/$name': typeof DesignNameRoute
  '/guides/$name': typeof GuidesNameRoute
  '/hooks/$name': typeof HooksNameRoute
  '/packages/$name': typeof PackagesNameRoute
  '/patterns/$name': typeof PatternsNameRoute
  '/visual-tests/$path': typeof VisualTestsPathRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/content/': typeof ContentIndexRoute
  '/design/': typeof DesignIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/hooks/': typeof HooksIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/patterns/': typeof PatternsIndexRoute
  '/visual-tests/': typeof VisualTestsIndexRoute
  '/components/$name/$tab': typeof ComponentsNameTabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/component-not-found'
    | '/welcome-guide'
    | '/changelog/$name'
    | '/components/$name'
    | '/content/$name'
    | '/design/$name'
    | '/guides/$name'
    | '/hooks/$name'
    | '/packages/$name'
    | '/patterns/$name'
    | '/visual-tests/$path'
    | '/changelog/'
    | '/components/'
    | '/content/'
    | '/design/'
    | '/guides/'
    | '/hooks/'
    | '/packages/'
    | '/patterns/'
    | '/visual-tests/'
    | '/components/$name/$tab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/component-not-found'
    | '/welcome-guide'
    | '/changelog/$name'
    | '/components/$name'
    | '/content/$name'
    | '/design/$name'
    | '/guides/$name'
    | '/hooks/$name'
    | '/packages/$name'
    | '/patterns/$name'
    | '/visual-tests/$path'
    | '/changelog'
    | '/components'
    | '/content'
    | '/design'
    | '/guides'
    | '/hooks'
    | '/packages'
    | '/patterns'
    | '/visual-tests'
    | '/components/$name/$tab'
  id:
    | '__root__'
    | '/'
    | '/component-not-found'
    | '/welcome-guide'
    | '/changelog/$name'
    | '/components/$name'
    | '/content/$name'
    | '/design/$name'
    | '/guides/$name'
    | '/hooks/$name'
    | '/packages/$name'
    | '/patterns/$name'
    | '/visual-tests/$path'
    | '/changelog/'
    | '/components/'
    | '/content/'
    | '/design/'
    | '/guides/'
    | '/hooks/'
    | '/packages/'
    | '/patterns/'
    | '/visual-tests/'
    | '/components/$name/$tab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentNotFoundRoute: typeof ComponentNotFoundRoute
  WelcomeGuideRoute: typeof WelcomeGuideRoute
  ChangelogNameRoute: typeof ChangelogNameRoute
  ComponentsNameRoute: typeof ComponentsNameRouteWithChildren
  ContentNameRoute: typeof ContentNameRoute
  DesignNameRoute: typeof DesignNameRoute
  GuidesNameRoute: typeof GuidesNameRoute
  HooksNameRoute: typeof HooksNameRoute
  PackagesNameRoute: typeof PackagesNameRoute
  PatternsNameRoute: typeof PatternsNameRoute
  VisualTestsPathRoute: typeof VisualTestsPathRoute
  ChangelogIndexRoute: typeof ChangelogIndexRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  ContentIndexRoute: typeof ContentIndexRoute
  DesignIndexRoute: typeof DesignIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  HooksIndexRoute: typeof HooksIndexRoute
  PackagesIndexRoute: typeof PackagesIndexRoute
  PatternsIndexRoute: typeof PatternsIndexRoute
  VisualTestsIndexRoute: typeof VisualTestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome-guide': {
      id: '/welcome-guide'
      path: '/welcome-guide'
      fullPath: '/welcome-guide'
      preLoaderRoute: typeof WelcomeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/component-not-found': {
      id: '/component-not-found'
      path: '/component-not-found'
      fullPath: '/component-not-found'
      preLoaderRoute: typeof ComponentNotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visual-tests/': {
      id: '/visual-tests/'
      path: '/visual-tests'
      fullPath: '/visual-tests/'
      preLoaderRoute: typeof VisualTestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns/': {
      id: '/patterns/'
      path: '/patterns'
      fullPath: '/patterns/'
      preLoaderRoute: typeof PatternsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/': {
      id: '/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof PackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/': {
      id: '/hooks/'
      path: '/hooks'
      fullPath: '/hooks/'
      preLoaderRoute: typeof HooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/': {
      id: '/design/'
      path: '/design'
      fullPath: '/design/'
      preLoaderRoute: typeof DesignIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/': {
      id: '/content/'
      path: '/content'
      fullPath: '/content/'
      preLoaderRoute: typeof ContentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/': {
      id: '/changelog/'
      path: '/changelog'
      fullPath: '/changelog/'
      preLoaderRoute: typeof ChangelogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visual-tests/$path': {
      id: '/visual-tests/$path'
      path: '/visual-tests/$path'
      fullPath: '/visual-tests/$path'
      preLoaderRoute: typeof VisualTestsPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns/$name': {
      id: '/patterns/$name'
      path: '/patterns/$name'
      fullPath: '/patterns/$name'
      preLoaderRoute: typeof PatternsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$name': {
      id: '/packages/$name'
      path: '/packages/$name'
      fullPath: '/packages/$name'
      preLoaderRoute: typeof PackagesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/$name': {
      id: '/hooks/$name'
      path: '/hooks/$name'
      fullPath: '/hooks/$name'
      preLoaderRoute: typeof HooksNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$name': {
      id: '/guides/$name'
      path: '/guides/$name'
      fullPath: '/guides/$name'
      preLoaderRoute: typeof GuidesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/$name': {
      id: '/design/$name'
      path: '/design/$name'
      fullPath: '/design/$name'
      preLoaderRoute: typeof DesignNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$name': {
      id: '/content/$name'
      path: '/content/$name'
      fullPath: '/content/$name'
      preLoaderRoute: typeof ContentNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$name': {
      id: '/components/$name'
      path: '/components/$name'
      fullPath: '/components/$name'
      preLoaderRoute: typeof ComponentsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/$name': {
      id: '/changelog/$name'
      path: '/changelog/$name'
      fullPath: '/changelog/$name'
      preLoaderRoute: typeof ChangelogNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$name/$tab': {
      id: '/components/$name/$tab'
      path: '/$tab'
      fullPath: '/components/$name/$tab'
      preLoaderRoute: typeof ComponentsNameTabRouteImport
      parentRoute: typeof ComponentsNameRoute
    }
  }
}

interface ComponentsNameRouteChildren {
  ComponentsNameTabRoute: typeof ComponentsNameTabRoute
}

const ComponentsNameRouteChildren: ComponentsNameRouteChildren = {
  ComponentsNameTabRoute: ComponentsNameTabRoute,
}

const ComponentsNameRouteWithChildren = ComponentsNameRoute._addFileChildren(
  ComponentsNameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentNotFoundRoute: ComponentNotFoundRoute,
  WelcomeGuideRoute: WelcomeGuideRoute,
  ChangelogNameRoute: ChangelogNameRoute,
  ComponentsNameRoute: ComponentsNameRouteWithChildren,
  ContentNameRoute: ContentNameRoute,
  DesignNameRoute: DesignNameRoute,
  GuidesNameRoute: GuidesNameRoute,
  HooksNameRoute: HooksNameRoute,
  PackagesNameRoute: PackagesNameRoute,
  PatternsNameRoute: PatternsNameRoute,
  VisualTestsPathRoute: VisualTestsPathRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  ContentIndexRoute: ContentIndexRoute,
  DesignIndexRoute: DesignIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  HooksIndexRoute: HooksIndexRoute,
  PackagesIndexRoute: PackagesIndexRoute,
  PatternsIndexRoute: PatternsIndexRoute,
  VisualTestsIndexRoute: VisualTestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
