# Always validate the PR title, and ignore the commits
titleOnly: true

# Valid scopes
scopes:
  - components
  - deps
  - design
  - docx
  - eslint
  - formatters
  - generators
  - hooks
  - stylelint
