import { InlineLabelColors } from "../InlineLabel";

const names = [
  "Jake Peralta",
  "Andy Samberg",
  "Rosa Diaz",
  "Stephanie Beatriz",
  "Terry Jeffords",
  "Terry Crews",
  "Amy Santiago",
  "Melissa Fumero",
  "Charles Boyle",
  "Joe Lo Truglio",
  "Gina Linetti",
  "Chelsea Peretti",
  "Raymond Holt",
  "Andre Braugher",
  "Michael Hitchcock",
  "Dirk Blocker",
  "Norm Scully",
  "Joel McKinnon Miller",
  "Mlepnos",
  "Fred Armisen",
  "Captain McGintley",
  "Mike Hagerty",
  "Commissioner Podolski",
  "James M. Connor",
  "The Vulture",
  "Dean Winters",
  "Zeke",
  "Jamal Duff",
  "Fire Marshal Boone",
  "Patton Oswalt",
  "Hank",
  "Kevin Dorff",
  "Doug Judy",
  "Craig Robinson",
  "Sharon Jeffords",
  "Merrin Dungey",
  "Vivian Ludley",
  "Marilu Henner",
  "Kevin Cozner",
  "Marc Evan Jackson",
  "Lohank",
  "Matt Walsh",
  "Teddy Wells",
  "Kyle Bornheimer",
  "Madeline Wuntch",
  "Kyra Sedgwick",
  "Sophia Perez",
  "Eva Longoria",
  "Lynn Boyle",
  "Stephen Root",
  "Darlene Linetti",
  "Sandra Bernhard",
  "Marcus",
  "Nick Cannon",
  "Geoffrey Hoytsman",
  "Chris Parnell",
  "Roger Peralta",
  "Bradley Whitford",
  "Oliver Cox",
  "Gabe Liedman",
  "Genevieve Mirren-Carter",
  "Mary Lynn Rajskub",
  "Adrian Pimento",
  "Jason Mantzoukas",
  "Maura Figgis",
  "Aida Turturro",
  "Bob Annderson",
  "Dennis Haysbert",
  "Karen Haas",
  "Maya Rudolph",
  "C.J. Stentley",
  "Ken Marino",
  "Sheriff Reynolds",
  "Jim O'Heir",
  "Nikolaj Boyle",
  "Antonio Raul Corbo",
  "Bill Hummertrout",
  "Veronica Hopkins",
  "Kimberly Hébert Gregory",
  "Melanie Hawkins",
  "Gina Gershon",
  "Caleb John Gosche",
  "Tim Meadows",
  "Jeff Romero",
  "Lou Diamond Phillips",
  "Warden Granville",
  "Toby Huss",
  "Seamus Murphy",
  "Paul Adelstein",
  "Olivia Crawford",
  "Allison Tolman",
  "Trudy Judy",
  "Nicole Byer",
  "John Kelly",
  "Phil Reeves",
  "Jocelyn Pryce",
  "Cameron Esposito",
  "Debbie Fogle",
  "Vanessa Bayer",
  "Frank O'Sullivan",
  "John C. McGinley",
];

const tags = [
  "night",
  "solution",
  "awareness",
  "opportunity",
  "satisfaction",
  "bedroom",
  "economics",
  "politics",
  "quality",
  "temperature",
  "chemistry",
  "village",
  "homework",
  "cousin",
  "gate",
  "employment",
  "information",
  "reality",
  "argument",
  "operation",
  "world",
  "chapter",
  "government",
  "establishment",
  "anxiety",
  "patience",
  "nation",
  "environment",
  "charity",
  "emotion",
  "topic",
  "camera",
  "analysis",
  "education",
  "honey",
  "appointment",
  "video",
  "winner",
  "relationship",
  "movie",
  "series",
  "mixture",
  "negotiation",
  "airport",
  "method",
  "procedure",
  "direction",
  "success",
  "foundation",
  "county",
];

const status: { label: string; color: InlineLabelColors }[] = [
  { label: "Active", color: "green" },
  { label: "Archived", color: "greyBlue" },
  { label: "Lead", color: "lightBlue" },
];

const address = [
  "Burdett Avenue, Victoria, British Columbia, V8W IE9",
  "Bellwood Acres Rd, Huntsville, Ontario, P0A 1K0",
  "Haaglund Rd, Oliver, British Columbia, V0H 1T0",
  "Bay Street, Toronto, Ontario, M5J 2R8",
  "Lynden Road, Moonstone, Ontario, L0K 1N0",
  "90th Avenue, Brooks, Alberta, T0J 0J0",
  "Alness Street, Toronto, Ontario, M3J 2J1",
  "Brew Creek Rd, Port Hardy, British Columbia, V0N 2P0",
  "Boulevard Ste-Geneviève, Chicoutimi, Quebec, G7H 5G3",
  "Ste. Catherine Ouest, Montreal, Quebec, H3A 4G4",
  "40th Street, Calgary, Alberta, T2A 1C8",
  "Duke Street, Montreal, Quebec, H3C 5K4",
  "Charing Cross Rd, Chatham, Ontario, N7M 2G9",
  "Eglinton Avenue, Toronto, Ontario, M4P 1A6",
  "40th Street, Calgary, Alberta, T2A 1C8",
  "43rd Avenue, Whitehorse, Yukon, Y1A 2A2",
];

function randomDate() {
  const start = new Date(2023, 6, 1);
  const end = new Date();
  return new Date(
    start.getTime() + Math.random() * (end.getTime() - start.getTime()),
  );
}

function getRandomIndex(max: number) {
  return Math.floor(Math.random() * max);
}

export const data = names.map((name, i) => ({
  id: i,
  name,
  tags: Array.from({ length: getRandomIndex(tags.length) }, () =>
    Math.floor(Math.random() * tags.length),
  ).map(tag => tags[tag]),
  status: status[getRandomIndex(status.length)],
  address: `${getRandomIndex(1000)} ${address[getRandomIndex(address.length)]}`,
  lastActiveDate: randomDate(),
  email: name.toLocaleLowerCase().split(" ").join(".") + "@gmail.com",
}));

export type DataArray = typeof data;
export type DataType = DataArray[number];
export type DataKeysType = keyof DataType;
