
add_type_linter_exceptions() {
  (printf '/* tslint:disable */\n/* eslint-disable */\n/* This file is automatically generated and should not be edited. */\n'; cat $1.d.ts) > $1.d.ts.temp
}

add_js_linter_exceptions() {
  (printf '/* tslint:disable */\n/* eslint-disable */\n/* This file is automatically generated and should not be edited. */\n'; cat $1.js) > $1.js.temp
}


add_type_linter_exceptions "foundation"
add_js_linter_exceptions "foundation"

add_type_linter_exceptions "foundation.ios"
add_js_linter_exceptions "foundation.ios"

add_type_linter_exceptions "foundation.android"
add_js_linter_exceptions "foundation.android"
