export const checkbox: string;
export const wrapper: string;
export const disabled: string;
export const checkHolder: string;
export const input: string;
export const checkBox: string;
export const indeterminate: string;
export const label: string;
export const description: string;
