declare const styles: {
  readonly "icon": string;
  readonly "longArrowUp": string;
  readonly "longArrowDown": string;
  readonly "thumbsDown": string;
  readonly "person": string;
  readonly "clients": string;
  readonly "company": string;
  readonly "property": string;
  readonly "job": string;
  readonly "jobOnHold": string;
  readonly "visit": string;
  readonly "moveVisits": string;
  readonly "event": string;
  readonly "quote": string;
  readonly "request": string;
  readonly "task": string;
  readonly "userUnassigned": string;
  readonly "reminder": string;
  readonly "trash": string;
  readonly "checkmark": string;
  readonly "timer": string;
  readonly "invoice": string;
  readonly "invoiceLater": string;
  readonly "sendInvoice": string;
  readonly "paidInvoice": string;
  readonly "badInvoice": string;
  readonly "payment": string;
  readonly "expense": string;
  readonly "video": string;
  readonly "excel": string;
  readonly "pdf": string;
  readonly "word": string;
};
export = styles;

