/* This file is automatically generated by buildIconStyle.js and should not be edited. */
export const iconStyles = {
  "icon": {
    "fill": "rgb(66, 78, 86)",
    "display": "inline-block",
    "verticalAlign": "middle"
  },
  "longArrowUp": {
    "transform": [
      {
        "rotate": "90deg"
      }
    ]
  },
  "longArrowDown": {
    "transform": [
      {
        "rotate": "-90deg"
      }
    ]
  },
  "thumbsDown": {
    "transform": [
      {
        "scaleY": -1
      }
    ]
  },
  "person": {
    "fill": "rgb(62, 173, 146)"
  },
  "clients": {
    "fill": "rgb(62, 173, 146)"
  },
  "company": {
    "fill": "rgb(62, 173, 146)"
  },
  "property": {
    "fill": "rgb(62, 173, 146)"
  },
  "job": {
    "fill": "rgb(187, 197, 32)"
  },
  "jobOnHold": {
    "fill": "rgb(187, 197, 32)"
  },
  "visit": {
    "fill": "rgb(153, 193, 70)"
  },
  "moveVisits": {
    "fill": "rgb(153, 193, 70)"
  },
  "event": {
    "fill": "rgb(221, 195, 15)"
  },
  "request": {
    "fill": "rgb(85, 106, 203)"
  },
  "userUnassigned": {
    "fill": "rgb(239, 87, 51)"
  },
  "reminder": {
    "fill": "rgb(239, 87, 51)"
  },
  "trash": {
    "fill": "rgb(239, 87, 51)"
  },
  "task": {
    "fill": "rgb(75, 106, 150)"
  },
  "timer": {
    "fill": "rgb(60, 162, 224)"
  },
  "quote": {
    "fill": "rgb(179, 96, 150)"
  },
  "invoice": {
    "fill": "rgb(136, 112, 196)"
  },
  "invoiceLater": {
    "fill": "rgb(136, 112, 196)"
  },
  "sendInvoice": {
    "fill": "rgb(136, 112, 196)"
  },
  "paidInvoice": {
    "fill": "rgb(136, 112, 196)"
  },
  "badInvoice": {
    "fill": "rgb(239, 87, 51)"
  },
  "payment": {
    "fill": "rgb(243, 150, 36)"
  },
  "expense": {
    "fill": "rgb(243, 150, 36)"
  },
  "edit": {
    "fill": "rgb(130, 107, 70)"
  },
  "archive": {
    "fill": "rgb(1, 41, 57)"
  },
  "excel": {
    "fill": "rgb(31, 115, 71)"
  },
  "file": {
    "fill": "rgba(101, 120, 132, 1)"
  },
  "pdf": {
    "fill": "rgb(195, 27, 0)"
  },
  "word": {
    "fill": "rgb(41, 86, 154)"
  },
  "video": {
    "fill": "rgb(60, 162, 224)"
  },
  "small": {
    "width": 16,
    "height": 16
  },
  "base": {
    "width": 24,
    "height": 24
  },
  "large": {
    "width": 32,
    "height": 32
  },
  "white": {
    "fill": "rgba(255, 255, 255, 1)"
  },
  "grey": {
    "fill": "rgb(181, 181, 181)"
  },
  "greyBlue": {
    "fill": "rgba(101, 120, 132, 1)"
  },
  "greyBlueDark": {
    "fill": "rgb(66, 78, 86)"
  },
  "blue": {
    "fill": "rgb(1, 41, 57)"
  },
  "lightBlue": {
    "fill": "rgb(60, 162, 224)"
  },
  "green": {
    "fill": "rgb(125, 176, 14)"
  },
  "yellow": {
    "fill": "rgb(221, 195, 15)"
  },
  "red": {
    "fill": "rgb(239, 87, 51)"
  },
  "navy": {
    "fill": "rgb(75, 106, 150)"
  },
  "orange": {
    "fill": "rgb(243, 150, 36)"
  },
  "interactive": {
    "fill": "rgb(125, 176, 14)"
  },
  "interactiveHover": {
    "fill": "rgb(81, 114, 9)"
  },
  "destructive": {
    "fill": "rgb(239, 87, 51)"
  },
  "destructiveHover": {
    "fill": "rgb(155, 57, 33)"
  },
  "interactiveSubtle": {
    "fill": "rgba(101, 120, 132, 1)"
  },
  "interactiveSubtleHover": {
    "fill": "rgb(66, 78, 86)"
  },
  "disabled": {
    "fill": "rgb(181, 181, 181)"
  },
  "disabledSecondary": {
    "fill": "rgb(225, 225, 225)"
  },
  "focus": {
    "fill": "rgb(231, 213, 87)"
  },
  "critical": {
    "fill": "rgb(239, 87, 51)"
  },
  "criticalSurface": {
    "fill": "rgb(253, 230, 224)"
  },
  "criticalOnSurface": {
    "fill": "rgb(155, 57, 33)"
  },
  "warning": {
    "fill": "rgb(221, 195, 15)"
  },
  "warningSurface": {
    "fill": "rgb(250, 246, 219)"
  },
  "warningOnSurface": {
    "fill": "rgb(144, 127, 10)"
  },
  "success": {
    "fill": "rgb(125, 176, 14)"
  },
  "successSurface": {
    "fill": "rgb(236, 243, 219)"
  },
  "successOnSurface": {
    "fill": "rgb(81, 114, 9)"
  },
  "informative": {
    "fill": "rgb(60, 162, 224)"
  },
  "informativeSurface": {
    "fill": "rgb(226, 241, 250)"
  },
  "informativeOnSurface": {
    "fill": "rgb(39, 105, 146)"
  },
  "inactive": {
    "fill": "rgb(77, 105, 116)"
  },
  "inactiveSurface": {
    "fill": "rgb(217, 223, 225)"
  },
  "inactiveOnSurface": {
    "fill": "rgb(1, 27, 37)"
  },
  "heading": {
    "fill": "rgb(1, 41, 57)"
  },
  "text": {
    "fill": "rgb(66, 78, 86)"
  },
  "textSecondary": {
    "fill": "rgba(101, 120, 132, 1)"
  },
  "textReverse": {
    "fill": "rgba(255, 255, 255, 1)"
  },
  "textReverseSecondary": {
    "fill": "rgb(193, 201, 206)"
  },
  "surface": {
    "fill": "rgba(255, 255, 255, 1)"
  },
  "surfaceHover": {
    "fill": "rgb(250, 246, 219)"
  },
  "surfaceActive": {
    "fill": "rgb(236, 243, 219)"
  },
  "surfaceBackground": {
    "fill": "rgb(244, 244, 244)"
  },
  "surfaceReverse": {
    "fill": "rgb(1, 41, 57)"
  },
  "brand": {
    "fill": "rgb(125, 176, 14)"
  },
  "brandHighlight": {
    "fill": "rgb(160, 215, 42)"
  }
}