export const list: string;
export const item: string;
export const action: string;
export const icon: string;
export const info: string;
export const amount: string;
export const isActive: string;
export const truncate: string;
export const sectionHeader: string;
