export const wrapper: string;
export const formField: string;
export const label: string;
export const inline: string;
export const small: string;
export const large: string;
export const invalid: string;
export const disabled: string;
export const hasValue: string;
