declare const styles: {
  readonly "container": string;
  readonly "wrapper": string;
  readonly "disabled": string;
  readonly "horizontalWrapper": string;
  readonly "textarea": string;
  readonly "safari": string;
  readonly "timeInputLabel": string;
  readonly "miniLabel": string;
  readonly "large": string;
  readonly "text": string;
  readonly "invalid": string;
  readonly "small": string;
  readonly "inline": string;
  readonly "center": string;
  readonly "right": string;
  readonly "maxLength": string;
  readonly "inputWrapper": string;
  readonly "childrenWrapper": string;
  readonly "input": string;
  readonly "emptyPhoneNumber": string;
  readonly "label": string;
  readonly "select": string;
  readonly "externalLabel": string;
  readonly "postfix": string;
  readonly "affixIcon": string;
  readonly "suffix": string;
  readonly "affixLabel": string;
  readonly "description": string;
  readonly "toolbar": string;
};
export = styles;

