#!/usr/bin/env ts-node  --project ./tsconfig.bin.json

import { readFileSync, readdirSync, statSync, writeFileSync } from "fs";
import { join, parse } from "path";
import { load } from "cheerio";

const iconFolder = join(__dirname, "../assets/icons");
const iconMap: { height: number; icons: Record<string, string[]> } = {
  height: 1024,
  icons: {},
};

const files: string[] = getFiles();
files.forEach(file => {
  const iconName = parse(file).name;
  const paths = extractSVGPaths(file);
  iconMap.icons[iconName] = paths;
});

writeFileSync(
  "packages/design/src/icons/iconMap.ts",
  `/* tslint:disable */
/* eslint-disable */
/* This file is automatically generated and should not be edited. */
/* Add your icons SVG file under assets/icons and run "npm run generateIconMap" */

export const iconMap = ${JSON.stringify(iconMap, undefined, 2)};`,
);

function getFiles(dirPath = iconFolder, arrayOfFiles: string[] = []) {
  const filePaths = readdirSync(dirPath);
  filePaths.forEach(function (file) {
    if (statSync(dirPath + "/" + file).isDirectory()) {
      arrayOfFiles = getFiles(dirPath + "/" + file, arrayOfFiles);
    } else {
      arrayOfFiles.push(`${dirPath}/${file}`);
    }
  });

  return arrayOfFiles;
}

function extractSVGPaths(path: string) {
  const data = readFileSync(path, "utf8");
  const $ = load(data, { xmlMode: true });
  const pathSet = $("path");

  return pathSet
    .map(function () {
      return $(this).attr("d");
    })
    .toArray();
}
