declare const styles: {
  readonly "inlineLabel": string;
  readonly "small": string;
  readonly "base": string;
  readonly "large": string;
  readonly "larger": string;
  readonly "greyBlue": string;
  readonly "red": string;
  readonly "orange": string;
  readonly "green": string;
  readonly "success": string;
  readonly "blue": string;
  readonly "inactive": string;
  readonly "navy": string;
  readonly "task": string;
  readonly "yellow": string;
  readonly "warning": string;
  readonly "lime": string;
  readonly "purple": string;
  readonly "invoice": string;
  readonly "pink": string;
  readonly "quote": string;
  readonly "teal": string;
  readonly "yellowGreen": string;
  readonly "job": string;
  readonly "blueDark": string;
  readonly "lightBlue": string;
  readonly "informative": string;
  readonly "indigo": string;
  readonly "request": string;
};
export = styles;

