declare const styles: {
  readonly inlineLabel: string;
  readonly base: string;
  readonly large: string;
  readonly larger: string;
  readonly greyBlue: string;
  readonly red: string;
  readonly orange: string;
  readonly green: string;
  readonly blue: string;
  readonly navy: string;
  readonly yellow: string;
  readonly lime: string;
  readonly purple: string;
  readonly pink: string;
  readonly teal: string;
  readonly yellowGreen: string;
  readonly blueDark: string;
  readonly lightBlue: string;
  readonly indigo: string;
};
export = styles;
