export const container: string;
export const modal: string;
export const header: string;
export const closeButton: string;
export const content: string;
export const actionBar: string;
export const leftAction: string;
export const rightAction: string;
export const overlay: string;
