/* eslint-env node */
module.exports = [
  "content",
  "display",
  "position",
  "float",
  "clear",

  "top",
  "right",
  "bottom",
  "left",

  "visibility",
  "z-index",

  "width",
  "height",
  "max-width",
  "max-height",
  "min-width",
  "min-height",

  "box-align",
  "box-flex",
  "box-orient",
  "box-pack",
  "box-shadow",
  "box-sizing",
  "table-layout",
  "resize",

  "margin",
  "margin-top",
  "margin-bottom",
  "margin-left",
  "margin-right",
  "margin-collapse",
  "margin-top-collapse",
  "margin-bottom-collapse",
  "margin-left-collapse",
  "margin-right-collapse",

  "padding",
  "padding-top",
  "padding-bottom",
  "padding-left",
  "padding-right",

  "border",
  "border-collapse",
  "border-top",
  "border-bottom",
  "border-left",
  "border-right",
  "border-color",
  "border-image",
  "border-top-color",
  "border-bottom-color",
  "border-left-color",
  "border-right-color",
  "border-spacing",
  "border-style",
  "border-top-style",
  "border-bottom-style",
  "border-left-style",
  "border-right-style",
  "border-width",
  "border-top-width",
  "border-bottom-width",
  "border-left-width",
  "border-right-width",
  "border-radius",
  "border-top-right-radius",
  "border-bottom-right-radius",
  "border-bottom-left-radius",
  "border-top-left-radius",
  "border-radius-topright",
  "border-radius-bottomright",
  "border-radius-bottomleft",
  "border-radius-topleft",

  "outline",
  "outline-offset",

  "overflow",
  "overflow-x",
  "overflow-y",

  "color",
  "font",
  "font-family",
  "font-size",
  "font-smoothing",
  "osx-font-smoothing",
  "font-style",
  "font-weight",
  "hyphens",
  "src",
  "line-height",
  "letter-spacing",
  "word-spacing",
  "text-align",
  "text-decoration",
  "text-indent",
  "text-overflow",
  "text-rendering",
  "text-size-adjust",
  "text-shadow",
  "text-transform",
  "word-break",
  "word-wrap",
  "white-space",
  "vertical-align",
  "quotes",
  "user-select",
  "speak",
  "speak-as",

  "list-style",
  "list-style-type",
  "list-style-position",
  "list-style-image",

  "background",
  "background-attachment",
  "background-color",
  "background-image",
  "background-position",
  "background-repeat",
  "background-size",
  "background-clip",

  "touch-action",
  "pointer-events",
  "cursor",

  "opacity",
  "filter",
  "size",
  "zoom",
  "transform",
  "backface-visibility",

  "animation",
  "animation-delay",
  "animation-duration",
  "animation-iteration-count",
  "animation-name",
  "animation-play-state",
  "animation-timing-function",
  "animation-fill-mode",
  "transition",
  "transition-delay",
  "transition-duration",
  "transition-property",
  "transition-timing-function",
  "will-change",

  "appearance",
  "interpolation-mode",
  "direction",
  "marks",
  "page",
  "set-link-source",
  "unicode-bidi",
];
