export const componentMap: Record<string, string> = {
  ActionLabel: "ActionLabel",
  Button: "Button",
  ButtonGroup: "ButtonGroup",
  IconButton: "IconButton",
  Autocomplete: "Autocomplete",
  Form: "Form",
  InputAvatar: "InputAvatar",
  InputCurrency: "InputCurrency",
  InputDate: "InputDate",
  InputEmail: "InputEmail",
  InputFile: "InputFile",
  InputGroup: "InputGroup",
  InputNumber: "InputNumber",
  InputPassword: "InputPassword",
  InputPhoneNumber: "InputPhoneNumber",
  InputPressable: "InputPressable",
  InputSearch: "InputSearch",
  InputText: "InputText",
  InputTime: "InputTime",
  InputValidation: "InputValidation",
  RadioGroup: "RadioGroup",
  Avatar: "Avatar",
  FormatFile: "FormatFile",
  Gallery: "Gallery",
  Icon: "Icon",
  LightBox: "LightBox",
  ThumbnailList: "ThumbnailList",
  ActionItem: "ActionItem",
  ActionItemGroup: "ActionItemGroup",
  Card: "Card",
  Content: "Content",
  Disclosure: "Disclosure",
  Divider: "Divider",
  Drawer: "Drawer",
  Flex: "Flex",
  Grid: "Grid",
  Page: "Page",
  DataList: "DataList",
  DataTable: "DataTable",
  DescriptionList: "DescriptionList",
  List: "List",
  Table: "Table",
  TextList: "TextList",
  Menu: "Menu",
  Tabs: "Tabs",
  ConfirmationModal: "ConfirmationModal",
  ContentOverlay: "ContentOverlay",
  Modal: "Modal",
  Popover: "Popover",
  SideDrawer: "SideDrawer",
  Tooltip: "Tooltip",
  BottomSheet: "BottomSheet",
  Checkbox: "Checkbox",
  Chip: "Chip",
  Chips: "Chips",
  Combobox: "Combobox",
  DatePicker: "DatePicker",
  FeatureSwitch: "FeatureSwitch",
  MultiSelect: "MultiSelect",
  RecurringSelect: "RecurringSelect",
  SegmentedControl: "SegmentedControl",
  Select: "Select",
  Switch: "Switch",
  ActivityIndicator: "ActivityIndicator",
  Banner: "Banner",
  EmptyState: "EmptyState",
  Glimmer: "Glimmer",
  InlineLabel: "InlineLabel",
  ProgressBar: "ProgressBar",
  Spinner: "Spinner",
  StatusIndicator: "StatusIndicator",
  StatusLabel: "StatusLabel",
  Toast: "Toast",
  AutoLink: "AutoLink",
  Emphasis: "Emphasis",
  Heading: "Heading",
  Link: "Link",
  Markdown: "Markdown",
  Text: "Text",
  Typography: "Typography",
  AnimatedPresence: "AnimatedPresence",
  AnimatedSwitcher: "AnimatedSwitcher",
  Countdown: "Countdown",
  DataDump: "DataDump",
  FormatDate: "FormatDate",
  FormatEmail: "FormatEmail",
  FormatRelativeDateTime: "FormatRelativeDateTime",
  Box: "Box",
  FormatTime: "FormatTime",
  // Design section
  Colors: "design/colors",
  Breakpoints: "design/breakpoints",
  Borders: "design/borders",
  Elevations: "design/elevations",
  Opacity: "design/opacity",
  Radii: "design/radii",
  Spacing: "design/spacing",
  DesignTypography: "design/typography",
};

export const getComponentPath = (componentName: string): string => {
  const mapped = componentMap[componentName];
  if (!mapped) return "/components";

  return mapped.startsWith("design/") ? `/${mapped}` : `/components/${mapped}`;
};
